//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaaseDBEntities : DbContext
    {
        //public MaaseDBEntities()
        //    : base("name=MaaseDBEntities")
        //{
        //}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<T_BankMyAcount> T_BankMyAcount { get; set; }
        public DbSet<T_BurdenInformations> T_BurdenInformations { get; set; }
        public DbSet<T_Consumer_Bank> T_Consumer_Bank { get; set; }
        public DbSet<T_ConsumerFinancialStatements> T_ConsumerFinancialStatements { get; set; }
        public DbSet<T_ConsumerProducePrices> T_ConsumerProducePrices { get; set; }
        public DbSet<T_Consumers> T_Consumers { get; set; }
        public DbSet<T_ConsumersPays> T_ConsumersPays { get; set; }
        public DbSet<T_FinancialStates> T_FinancialStates { get; set; }
        public DbSet<T_PayState> T_PayState { get; set; }
        public DbSet<T_PayType> T_PayType { get; set; }
        public DbSet<T_Producer_Pay_Title> T_Producer_Pay_Title { get; set; }
        public DbSet<T_ProducerFinancialStatements> T_ProducerFinancialStatements { get; set; }
        public DbSet<T_ProducerProducePrices> T_ProducerProducePrices { get; set; }
        public DbSet<T_Producers> T_Producers { get; set; }
        public DbSet<T_ProducersPays> T_ProducersPays { get; set; }
        public DbSet<T_Produces> T_Produces { get; set; }
        public DbSet<T_RecoveryAgent> T_RecoveryAgent { get; set; }
        public DbSet<T_State> T_State { get; set; }
        public DbSet<T_TransportPrices> T_TransportPrices { get; set; }
        public DbSet<T_Truck_Pay_Title> T_Truck_Pay_Title { get; set; }
        public DbSet<T_TruckFinancialStatements> T_TruckFinancialStatements { get; set; }
        public DbSet<T_Trucks> T_Trucks { get; set; }
        public DbSet<T_TrucksPays> T_TrucksPays { get; set; }
        public DbSet<T_UserRoles> T_UserRoles { get; set; }
        public DbSet<T_Users> T_Users { get; set; }
        public DbSet<T_Users_Type> T_Users_Type { get; set; }
        public DbSet<T_UsersInRoles> T_UsersInRoles { get; set; }
    }
}
