//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BurdenInformations
    {
        public long BurdenInformationID { get; set; }
        public Nullable<int> TruckID { get; set; }
        public string LoadDateTime { get; set; }
        public Nullable<float> LoadFullTruckWeight { get; set; }
        public Nullable<float> LoadFreeTruckWeight { get; set; }
        public string UnLoadDateTime { get; set; }
        public Nullable<float> UnLoadFullTruckWeight { get; set; }
        public Nullable<float> UnLoadFreeTruckWeight { get; set; }
        public Nullable<int> TransportPriceID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ResidUnLoudNumber { get; set; }
        public string ResidLoudNumber { get; set; }
        public string RegisterDateTime { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<int> CPPID { get; set; }
        public Nullable<int> PPPID { get; set; }
        public Nullable<long> PFSID { get; set; }
        public Nullable<long> CFSID { get; set; }
        public Nullable<long> TFSID { get; set; }
    
        public virtual T_TransportPrices T_TransportPrices { get; set; }
        public virtual T_Trucks T_Trucks { get; set; }
        public virtual T_ConsumerFinancialStatements T_ConsumerFinancialStatements { get; set; }
        public virtual T_ConsumerProducePrices T_ConsumerProducePrices { get; set; }
        public virtual T_ProducerFinancialStatements T_ProducerFinancialStatements { get; set; }
        public virtual T_ProducerProducePrices T_ProducerProducePrices { get; set; }
        public virtual T_TruckFinancialStatements T_TruckFinancialStatements { get; set; }
        public virtual T_Users T_Users { get; set; }
    }
}
