//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Consumer_Bank
    {
        public T_Consumer_Bank()
        {
            this.T_ConsumersPays = new HashSet<T_ConsumersPays>();
        }
    
        public short BankID { get; set; }
        public string BankName { get; set; }
    
        public virtual ICollection<T_ConsumersPays> T_ConsumersPays { get; set; }
    }
}
