//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ConsumerFinancialStatements
    {
        public T_ConsumerFinancialStatements()
        {
            this.T_BurdenInformations = new HashSet<T_BurdenInformations>();
            this.T_ConsumersPays = new HashSet<T_ConsumersPays>();
        }
    
        public long ConsumerFinancialStatementID { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string Descryption { get; set; }
        public int ConsumerID { get; set; }
        public short StateID { get; set; }
    
        public virtual ICollection<T_BurdenInformations> T_BurdenInformations { get; set; }
        public virtual T_Consumers T_Consumers { get; set; }
        public virtual T_FinancialStates T_FinancialStates { get; set; }
        public virtual ICollection<T_ConsumersPays> T_ConsumersPays { get; set; }
    }
}
