//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ConsumersPays
    {
        public long ConsumerPayID { get; set; }
        public long CFSID { get; set; }
        public string PayDate { get; set; }
        public string RegisterDate { get; set; }
        public short PayTypeID { get; set; }
        public short PayStateID { get; set; }
        public decimal Price { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public string Owner { get; set; }
        public short BankId { get; set; }
        public string Bankdepartment { get; set; }
        public string RecoveryDate { get; set; }
        public short AgentID { get; set; }
    
        public virtual T_Consumer_Bank T_Consumer_Bank { get; set; }
        public virtual T_ConsumerFinancialStatements T_ConsumerFinancialStatements { get; set; }
        public virtual T_PayState T_PayState { get; set; }
        public virtual T_PayType T_PayType { get; set; }
        public virtual T_RecoveryAgent T_RecoveryAgent { get; set; }
    }
}
