//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Consumers
    {
        public T_Consumers()
        {
            this.T_ConsumerFinancialStatements = new HashSet<T_ConsumerFinancialStatements>();
            this.T_ConsumerProducePrices = new HashSet<T_ConsumerProducePrices>();
            this.T_TransportPrices = new HashSet<T_TransportPrices>();
        }
    
        public int ConsumerID { get; set; }
        public string CompanyName { get; set; }
        public string OwnerFullName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Descryption { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string EmailAddress { get; set; }
        public bool StateID { get; set; }
    
        public virtual ICollection<T_ConsumerFinancialStatements> T_ConsumerFinancialStatements { get; set; }
        public virtual ICollection<T_ConsumerProducePrices> T_ConsumerProducePrices { get; set; }
        public virtual ICollection<T_TransportPrices> T_TransportPrices { get; set; }
        public virtual T_State T_State { get; set; }
    }
}
