//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FinancialStates
    {
        public T_FinancialStates()
        {
            this.T_ConsumerFinancialStatements = new HashSet<T_ConsumerFinancialStatements>();
            this.T_ProducerFinancialStatements = new HashSet<T_ProducerFinancialStatements>();
            this.T_TruckFinancialStatements = new HashSet<T_TruckFinancialStatements>();
        }
    
        public short StateID { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<T_ConsumerFinancialStatements> T_ConsumerFinancialStatements { get; set; }
        public virtual ICollection<T_ProducerFinancialStatements> T_ProducerFinancialStatements { get; set; }
        public virtual ICollection<T_TruckFinancialStatements> T_TruckFinancialStatements { get; set; }
    }
}
