//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PayState
    {
        public T_PayState()
        {
            this.T_ConsumersPays = new HashSet<T_ConsumersPays>();
            this.T_ProducersPays = new HashSet<T_ProducersPays>();
            this.T_TrucksPays = new HashSet<T_TrucksPays>();
        }
    
        public short PayStateID { get; set; }
        public string PayStateName { get; set; }
    
        public virtual ICollection<T_ConsumersPays> T_ConsumersPays { get; set; }
        public virtual ICollection<T_ProducersPays> T_ProducersPays { get; set; }
        public virtual ICollection<T_TrucksPays> T_TrucksPays { get; set; }
    }
}
