//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Produces
    {
        public T_Produces()
        {
            this.T_ConsumerProducePrices = new HashSet<T_ConsumerProducePrices>();
            this.T_ProducerProducePrices = new HashSet<T_ProducerProducePrices>();
            this.T_TransportPrices = new HashSet<T_TransportPrices>();
        }
    
        public int ProduceID { get; set; }
        public string ProduceName { get; set; }
        public string Descryption { get; set; }
    
        public virtual ICollection<T_ConsumerProducePrices> T_ConsumerProducePrices { get; set; }
        public virtual ICollection<T_ProducerProducePrices> T_ProducerProducePrices { get; set; }
        public virtual ICollection<T_TransportPrices> T_TransportPrices { get; set; }
    }
}
