//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProducersPays
    {
        public long ProducerPayID { get; set; }
        public long PFSID { get; set; }
        public string PayDate { get; set; }
        public string RegisterDate { get; set; }
        public short PayTypeID { get; set; }
        public short PayStateID { get; set; }
        public decimal Price { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public short BankId { get; set; }
        public string RecoveryDate { get; set; }
        public short TitleID { get; set; }
    
        public virtual T_BankMyAcount T_BankMyAcount { get; set; }
        public virtual T_PayState T_PayState { get; set; }
        public virtual T_PayType T_PayType { get; set; }
        public virtual T_Producer_Pay_Title T_Producer_Pay_Title { get; set; }
        public virtual T_ProducerFinancialStatements T_ProducerFinancialStatements { get; set; }
    }
}
