//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Producers
    {
        public T_Producers()
        {
            this.T_ProducerFinancialStatements = new HashSet<T_ProducerFinancialStatements>();
            this.T_ProducerProducePrices = new HashSet<T_ProducerProducePrices>();
            this.T_TransportPrices = new HashSet<T_TransportPrices>();
        }
    
        public int ProducerID { get; set; }
        public string CompanyName { get; set; }
        public string OwnerFullName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Descryption { get; set; }
        public bool StateID { get; set; }
    
        public virtual ICollection<T_ProducerFinancialStatements> T_ProducerFinancialStatements { get; set; }
        public virtual ICollection<T_ProducerProducePrices> T_ProducerProducePrices { get; set; }
        public virtual ICollection<T_TransportPrices> T_TransportPrices { get; set; }
        public virtual T_State T_State { get; set; }
    }
}
