//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Trucks
    {
        public T_Trucks()
        {
            this.T_BurdenInformations = new HashSet<T_BurdenInformations>();
            this.T_TruckFinancialStatements = new HashSet<T_TruckFinancialStatements>();
        }
    
        public int TruckID { get; set; }
        public string Number { get; set; }
        public string OwnerFullName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> PureWeight { get; set; }
        public string Descryption { get; set; }
        public bool StateID { get; set; }
    
        public virtual ICollection<T_BurdenInformations> T_BurdenInformations { get; set; }
        public virtual T_State T_State { get; set; }
        public virtual ICollection<T_TruckFinancialStatements> T_TruckFinancialStatements { get; set; }
    }
}
