//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Users
    {
        public T_Users()
        {
            this.T_BurdenInformations = new HashSet<T_BurdenInformations>();
            this.T_UsersInRoles = new HashSet<T_UsersInRoles>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<short> TypeID { get; set; }
        public Nullable<short> State { get; set; }
        public Nullable<int> PublicID { get; set; }
    
        public virtual ICollection<T_BurdenInformations> T_BurdenInformations { get; set; }
        public virtual T_Users_Type T_Users_Type { get; set; }
        public virtual ICollection<T_UsersInRoles> T_UsersInRoles { get; set; }
    }
}
