//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Users_Type
    {
        public T_Users_Type()
        {
            this.T_Users = new HashSet<T_Users>();
        }
    
        public short TypeID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<T_Users> T_Users { get; set; }
    }
}
