//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaseShooei.Areas.Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UsersInRoles
    {
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public long ID { get; set; }
    
        public virtual T_UserRoles T_UserRoles { get; set; }
        public virtual T_Users T_Users { get; set; }
    }
}
